variables:
  project: '$(Build.SourcesDirectory)/csharp/livetext-sharp.csproj'
  buildConfiguration: 'Release'
  targetVersion: yy.M.$(build.buildId)

trigger:
- main

pool:
  vmImage: 'macOS-latest'

steps:

- task: PowerShell@2
  displayName: 'Create CalVer Version'
  inputs:
    targetType: 'inline'
    script: |
      $dottedDate = (Get-Date).ToString("yy.M")
      $buildID = $($env:BUILD_BUILDID)
      $modBuildID = [int]$buildID % 65536  # ensure fits in int16
      $newTargetVersion = "$dottedDate.$modBuildID"
      Write-Host "##vso[task.setvariable variable=targetVersion;]$newTargetVersion"
      Write-Host "Updated targetVersion to '$newTargetVersion'"

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET 10.0 SDK'
  inputs:
    packageType: sdk
    version: 10.x
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: CmdLine@2
  inputs:
    script: |
      cd $(Build.SourcesDirectory)/swift
      rm $(Build.SourcesDirectory)/csharp/livetext-sharp
      swift build -c release --arch arm64 --arch x86_64
      lipo -info .build/apple/Products/Release/livetext-sharp
      cp .build/apple/Products/Release/livetext-sharp $(Build.SourcesDirectory)/csharp/livetext-sharp
      ls -aR $(Build.SourcesDirectory)

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c $(buildConfiguration) /p:Version=$(targetVersion)  /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    versioningScheme: 'off'
    configuration: 'Release'
    buildProperties: 'Version="$(targetVersion)";AllowUnsafeBlocks="True";LangVersion="latest"'
    verbosityPack: 'Diagnostic'
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'
